### ISSUE TITLE
WiiUDiscContentsHeader MAGIC Mismatch

### ISSUE THREAD

**Issue by Bubblebuy123** [Maschell/JWUDTool#11]
I keep getting this error, but I don't understand. I hope you can help me.
Ps I write with the google translator because my english is not very good.
![error](https://user-images.githubusercontent.com/85798194/121780820-5409c900-cba2-11eb-9c5d-067bf1902f9b.PNG)

**Comment by RxdRvse** [comment]
I'm having the same issue..   I dont know if the developer is gonna answer though /:

**Comment by jcarnell** [comment]
I know I'm digging up an old issue, but it means the game key entered does not match the game content.

**Comment by Bubblebuy123** [comment]
Sorry I haven't written yet, the issue has already been resolved. I figured it out myself. Thanks for replying anyway. I've completely forgotten.
Written with Google translator. Please ignore spelling mistakes.

**Comment by halevalente** [comment]
@Bubblebuy123 Hello sir, I am experiencing the same issue. Can you explain how you solved it, please?

**Comment by jcarnell** [comment]
Make sure the game.key that you have with the wud is correct. If you get that error, copy the game.key again then retry.

**Comment by alexdeivid** [comment]
For other people with this problem, the solution for me, was set mannualy the keyes, like this: 
java -jar JWUDTool.jar -in "CODBO2.wux" -out "extracted" -extract all -titleKey "638b01f6669fdec181ae664cf28e2d5d" -commonkey "d7b00402659ba2abd2cb0db27fa2b656"
This way the app find the title and extract to the folder.

**Comment by Fitsneezy** [comment]
C:\Users\#####\Downloads>java -jar jwudtool-0.4.jar -commonkey A851D78AB8F0A6FE1E93CFCEAF99A179 -titleKey f098695b99e792337d25f1c63935da45 -in "C:\Users\#####\Downloads\New folder\The Legend of Zelda - Breath of the Wild (USA) (DLC) (v208).wud" -decrypt
JWUDTool 0.4 - Maschell

Commonkey was set to: A851D78AB8F0A6FE1E93CFCEAF99A179
Titlekey was set to: F098695B99E792337D25F1C63935DA45
Decrypting full game partition.
Decrypting: C:\Users\#####\Downloads\New folder\The Legend of Zelda - Breath of the Wild (USA) (DLC) (v208).wud
Exception in thread "main" java.io.IOException: DiscId MAGIC mismatch.
        at de.mas.wiiu.jnus.implementations.wud.header.WiiUDiscID.parseData(WiiUDiscID.java:33)
        at de.mas.wiiu.jnus.implementations.wud.header.WiiUDiscHeader.parseData(WiiUDiscHeader.java:23)
        at de.mas.wiiu.jnus.implementations.wud.WiiUDisc.parseData(WiiUDisc.java:20)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:91)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:69)
        at de.mas.jwudtool.Main.decryptFile(Main.java:258)
        at de.mas.jwudtool.Main.decrypt(Main.java:301)
        at de.mas.jwudtool.Main.main(Main.java:153)

C:\Users\#####\Downloads>

same problem but with botw us dlc
hashtags over actual user folder for my security :D

**Comment by N0N0** [comment]
I had to provide commonkey and titleKey via CLI-parameters. 
Providing the titleKey from game.key always results in that error for me.

**Comment by kawaiinightcore** [comment]
Hey, what are the gamekeys for Just Dance Wii U?

**Comment by Fitsneezy** [comment]
idk

**Comment by Fitsneezy** [comment]
which one?

**Comment by Fitsneezy** [comment]
check https://gist.github.com/xXPhenomXx/093b352723ec51644453a9528a8dc87e to get it

**Comment by kawaiinightcore** [comment]
It isn't because Just Dance Wii U isn't on the NUS.

**Comment by kawaiinightcore** [comment]
I'm looking for Just Dance Wii U, a Japanese exclusive; its ID is 0005000010168f00

**Comment by kawaiinightcore** [comment]
java.security.InvalidKeyException: Invalid AES key length: 33 bytes

**Comment by Fitsneezy** [comment]
oh.
Idk then.
I'm not really a pro at this stuff.
