### ISSUE TITLE
common.key file (Note: I am not asking for the file)

### ISSUE THREAD

**Issue by Korozin** [Maschell/JWUDTool#12]
would anyone be so kind as to provide me with the information of how to CREATE a common.key file to be used, I have some basic knowledge of how so please correct me if I'm wrong..    Make a new file with NO characters in it and name it common.key and open it in a HEX Editor and add the common key to the bottom of the values and press save. Am I correct or am I not, some clarification would be GREATLY appreciated

**Comment by RxdRvse** [comment]
Also I am asking since I am unable to use USB Helper so resorting to other means of extracting the .app and .h3 files for use on my own wii u

**Comment by ghost** [comment]
Issue resolved.
