### ISSUE TITLE
JWUDTool-0.4 Doesn't open

### ISSUE THREAD

**Issue by Matthewkyos** [Maschell/JWUDTool#15]
Windows 11 
Won't Open in Java SE platform. run as admin doesn't work either no pop ups

**Comment by madrxx** [comment]
I thought I was also having this problem before realising it's a command line tool. you need to use Windows Terminal, Command Prompt or Powershell, navigate to the directory, then use `java -jar <the name of the JWUDTool jarfile>` and then add any extra arguments for JWUDTool on the end

**Comment by Matthewkyos** [comment]
> I thought I was also having this problem before realising it's a command line tool. you need to use Windows Terminal, Command Prompt or Powershell, navigate to the directory, then use `java -jar <the name of the JWUDTool jarfile>` and then add any extra arguments for JWUDTool on the end

Oh??? I didn't know that thanks!
