### ISSUE TITLE
Cannot Export game, no TitleKey available, -dev not functioning.

### ISSUE THREAD

**Issue by Jonah-multi** [Maschell/JWUDTool#23]
I'm trying to export Skylanders Giants, there's no titlekey for it(ref.1) and even when using -dev, supposedly used for when there is no titlekey, I still get a MAGIC error whenever I try exporting it.(ref.2), following the solutions in #11 doesn't work either due to lack of TitleKey.
![image](https://github.com/Maschell/JWUDTool/assets/54161865/6c98db7e-1d38-4f95-9f8e-898753cb9bdf)
![image](https://github.com/Maschell/JWUDTool/assets/54161865/eeca9e32-7fe5-4c61-8d5d-f13cf51f9ec5)

**Comment by Maschell** [comment]
You need you use the game.key that gets dumped next to the wud/wux

**Comment by Jonah-multi** [comment]
Yes, unfortunately I couldn't find it, however I did find a more comprehensive list of Wii U Title Keys, if others run into this issue, just keep looking, it may be harder to find, but you'll eventually find what you're looking for.
